# Choosing the root handler as the file handler
# to write log messages to a file.
# engine.logs.SystemOutHandler replaces ConsoleHandler (not anymore because it hides exceptions)
# java.util.logging.FileHandler allows to write the logs in a file (in folder build/jul-logs/)
handlers = java.util.logging.FileHandler
# Choosing a formatter for the console handler
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
engine.logs.SystemOutHandler.formatter = java.util.logging.SimpleFormatter
# setting the level for the console handler
java.util.logging.FileHandler.level = INFO
# logging is cumulative, appending at each execution
java.util.logging.FileHandler.append = true
# each log file can grow up to 5MB
java.util.logging.FileHandler.limit = 5000000
# keep up to 5 rotated files
# (rotation happens upon reaching the maximum size)
# once 5 files have been used, JUL wraps around
# and overwrites the oldest log file
java.util.logging.FileHandler.count = 5
# This defines the file name pattern used by JUL
# to create the log files
java.util.logging.FileHandler.pattern = build/jul-logs/global-%u-%g.log
# this is setting the level for the root logger
# and thus this is inherited by all loggers
.level = FINEST

java.util.logging.ConsoleHandler.level = FINEST
engine.logs.SystemOutHandler.level = FINEST

oop.utils.SoundPlayer.level = FINEST